service: utils-r3js-com

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-3
  memorySize: 512
  deploymentBucket:
    name: deployment-bucket-paris
  env:
    # LOG: true

functions:
  geo:
    handler: handler.geo
    events:
      - http:
          path: geo
          method: get